(() => {
  "use strict";
  // This is a browser-side convenience gate, not server-side authentication.
  // Replace the hash below with the SHA-256 hash of your chosen password.
  const ADMIN_PASSWORD_SHA256 = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9";
  const app = window.Portfolio;
  const publisher = window.PortfolioPublisher;
  const dashboard = document.getElementById("dashboard");
  const content = document.getElementById("editor-content");
  const preview = document.querySelector(".editor-preview iframe");
  const status = document.getElementById("editor-status");
  const tabs = ["Hero","About","Skills","Experience","Projects","Education","Contact","Headings","Backups"];
  let authenticated = false;
  let draft = null;
  let activeTab = "Hero";
  let dirty = false;
  let pendingConfirmation = null;
  let importedInput = null;
  let remoteHead = "";
  let publishing = false;
  let pendingPublish = null;
  const dialog = document.getElementById("confirm-dialog");
  const node = (tag, className, text) => { const result = document.createElement(tag); if (className) result.className = className; if (text !== undefined) result.textContent = app.noDigits(text); return result; };
  function notify(message, error = false) { status.textContent = app.noDigits(message); status.classList.toggle("error", error); }
  function syncPreview() { if (authenticated) preview.contentWindow?.Portfolio?.render(draft); }
  function changed() { dirty = true; pendingPublish = null; notify("Unsaved changes. Your preview is up to date."); syncPreview(); }
  function confirmAction(message, action) {
    if (!dirty) { action(); return; }
    pendingConfirmation = action; document.getElementById("confirm-message").textContent = message; dialog.showModal();
  }
  document.getElementById("confirm-cancel").addEventListener("click", () => { pendingConfirmation = null; dialog.close(); });
  document.getElementById("confirm-accept").addEventListener("click", () => { const action = pendingConfirmation; pendingConfirmation = null; dialog.close(); action?.(); });
  dialog.addEventListener("cancel", () => { pendingConfirmation = null; });
  function textField(parent, label, value, onChange, options = {}) {
    const wrapper = node("label", "field" + (options.wide ? " wide" : "")); wrapper.append(node("span", "", label));
    const input = node(options.multiline ? "textarea" : "input");
    if (!options.multiline) input.type = "text";
    input.value = app.encode(value); input.maxLength = 12000; input.spellcheck = !options.link;
    input.addEventListener("input", () => {
      const start = input.selectionStart;
      const left = app.encode(input.value.slice(0, start));
      input.value = app.encode(input.value); input.setSelectionRange(left.length, left.length);
      onChange(app.decode(input.value)); changed();
    }); wrapper.append(input); parent.append(wrapper); return input;
  }
  function fields(parent, model, definitions) {
    const grid = node("div", "editor-grid");
    definitions.forEach(([key, label, multiline = false, link = false]) => textField(grid, label, model[key], value => { model[key] = value; }, {multiline, wide:multiline, link}));
    parent.append(grid);
  }
  function button(parent, label, action, className = "button secondary") { const result = node("button", className, label); result.type = "button"; result.addEventListener("click", action); parent.append(result); return result; }
  function listEditor(key, singular, makeItem, definitions, extra) {
    if (!draft[key].length) content.append(node("p", "empty-note", "Nothing here yet. Add an entry to get started."));
    draft[key].forEach((item, index) => {
      const card = node("article", "editor-item"); const header = node("div", "editor-item-header");
      header.append(node("h3", "", item.title || item.name || item.degree || "New " + singular.toLowerCase()));
      button(header, "Remove", () => { draft[key].splice(index, 1); changed(); showTab(activeTab); }, "small-button remove-button"); card.append(header);
      fields(card, item, definitions); extra?.(card, item); content.append(card);
    });
    button(content, "Add " + singular.toLowerCase(), () => { draft[key].push(makeItem()); changed(); showTab(activeTab); content.querySelector(".editor-item:last-of-type input")?.focus(); });
  }
  function download(filename, text, type) {
    const url = URL.createObjectURL(new Blob([text], {type})); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  function safeExport(publication = false) {
    try {
      const clean = app.validate(draft);
      if (publication) download("data.js", "// Published portfolio content. Generated by the portfolio editor.\nwindow.PORTFOLIO_DEFAULTS = " + JSON.stringify(clean, null, 2) + ";\n", "text/javascript");
      else download("portfolio-backup.json", JSON.stringify(clean, null, 2), "application/json");
      notify(publication ? "Data file exported. Also export the SEO homepage and upload both files to GitHub." : "Backup exported, including your current draft.");
    } catch(error) { notify(error.message, true); }
  }
  function exportHomepage() {
    try {
      const portfolio = preview.contentWindow?.Portfolio;
      if (!portfolio?.exportHtml) throw new Error("Wait for the portfolio preview to finish loading, then try again.");
      download("index.html", portfolio.exportHtml(app.validate(draft)), "text/html");
      notify("Homepage exported with your current content and search metadata. Upload it beside admin.html, together with the matching data file in the JavaScript folder.");
    } catch (error) { notify(error.message, true); }
  }
  function backups() {
    content.append(node("p", "backup-note", "Export JSON to keep a backup of your current draft. Import a backup to preview its content, then choose Save Changes to keep it in this browser."));
    const actions = node("div", "backup-actions"); button(actions, "Export JSON", () => safeExport());
    button(actions, "Restore browser draft", () => confirmAction("Replace your current edits with the draft saved in this browser?", () => { draft = app.load(); changed(); showTab("Hero"); }));
    importedInput = node("input"); importedInput.type = "file"; importedInput.accept = ".json,application/json"; importedInput.hidden = true;
    button(actions, "Import JSON", () => importedInput.click());
    importedInput.addEventListener("change", async () => {
      const file = importedInput.files[0]; if (!file) return;
      try {
        if (file.size > 1000000) throw new Error("This backup is too large.");
        const imported = app.validate(JSON.parse(await file.text()));
        confirmAction("Importing replaces the current draft. Export a backup first if you want to keep it.", () => { draft = imported; changed(); notify("Backup imported as a draft. Review the preview, then save your changes."); showTab("Hero"); });
      } catch(error) { notify(error instanceof SyntaxError ? "This file is not valid JSON. Choose a portfolio backup." : error.message, true); }
      importedInput.value = "";
    }); content.append(actions, importedInput);
    content.append(node("h3", "", "Publish your edits")); content.append(node("p", "backup-note", "Export both files from the same draft: upload the publication file into the JavaScript folder, and upload the SEO homepage at the repository root beside admin.html. This keeps the visible portfolio and its search metadata in sync. Commit both files together on GitHub to publish them for everyone."));
    button(content, "Export publication file", () => safeExport(true));
    button(content, "Export SEO homepage", exportHomepage);
  }
  function showTab(label) {
    if (!authenticated) return;
    activeTab = label; content.replaceChildren(node("h2", "", label)); content.setAttribute("aria-labelledby", "tab-" + label.toLowerCase());
    document.querySelectorAll(".editor-nav button").forEach(tab => { const selected = tab.textContent === label; tab.setAttribute("aria-selected", String(selected)); tab.tabIndex = selected ? 0 : -1; });
    if (label === "Hero") fields(content, draft.hero, [["name","Name"],["title","Professional title"],["tagline","Tagline",true],["status","Availability"],["location","Location line"],["primaryLabel","Primary button label"],["primaryUrl","Primary button link",false,true],["secondaryLabel","Secondary button label"],["secondaryUrl","Secondary button link",false,true],["focusLabel","Feature card introduction"],["focusKicker","Feature card label"],["focusTitle","Feature card headline",true],["focusFooter","Feature card footer",true]]);
    if (label === "About") fields(content, draft.about, [["heading","Heading",true],["text","About you",true],["learning","Learning interests",true]]);
    if (label === "Skills") listEditor("skills","Skill",() => ({name:"New skill",percentage:null}),[["name","Skill name"]],(card,skill) => {
      const checkLabel = node("label","check-label"); const check = node("input"); check.type="checkbox"; check.checked=skill.percentage!==null; checkLabel.append(check,node("span","","Show self-assessed proficiency")); card.append(checkLabel);
      const rangeLabel = node("label","field"); rangeLabel.hidden=!check.checked; rangeLabel.append(node("span","","Proficiency")); const range=node("input"); range.type="range"; range.min="0";range.max="100";range.value=skill.percentage??50;range.setAttribute("aria-valuetext",app.noDigits(range.value)+" percent");rangeLabel.append(range); card.append(rangeLabel);
      check.addEventListener("change",()=>{skill.percentage=check.checked?Number(range.value):null;rangeLabel.hidden=!check.checked;changed();});
      range.addEventListener("input",()=>{skill.percentage=Number(range.value);range.setAttribute("aria-valuetext",app.noDigits(range.value)+" percent");changed();});
    });
    if (label === "Experience") listEditor("experience","Experience",()=>({title:"New role",company:"",location:"",period:"",bullets:[]}),[["title","Job title"],["company","Employer"],["location","Location"],["period","Dates written in words"]],(card,item)=>textField(card,"Highlights — each on its own line",item.bullets.join("\n"),value=>{item.bullets=value.split("\n").filter(line=>line.trim());},{multiline:true}));
    if (label === "Projects") listEditor("projects","Project",()=>({title:"New project",category:"",description:"",institution:"",tags:[],url:"",linkLabel:"View project"}),[["title","Project name"],["category","Category"],["description","Description",true],["institution","Institution or context"],["url","Project link",false,true],["linkLabel","Link label"]],(card,item)=>textField(card,"Tags — each on its own line",item.tags.join("\n"),value=>{item.tags=value.split("\n").filter(line=>line.trim());},{multiline:true}));
    if (label === "Education") listEditor("education","Education",()=>({degree:"New qualification",institution:"",period:"",description:""}),[["degree","Qualification"],["institution","Institution"],["period","Dates written in words"],["description","Additional details",true]]);
    if (label === "Contact") { fields(content,draft.contact,[["eyebrow","Introductory label"],["heading","Heading",true],["text","Invitation",true],["email","Email address",false,true],["phone","Phone number",false,true],["linkedin","LinkedIn profile link",false,true],["location","Location"],["emailLabel","Email button label"],["phoneLabel","Phone button label"],["linkedinLabel","LinkedIn button label"]]);content.append(node("p","muted","Leave LinkedIn blank until your profile link is ready.")); }
    if (label === "Headings") fields(content,draft.headings,[["skills","Skills heading"],["experience","Experience heading"],["projects","Projects heading"],["projectsIntro","Projects introduction",true],["education","Education heading"],["footer","Footer text",true]]);
    if (label === "Backups") backups();
  }
  tabs.forEach(label => { const tab = button(document.querySelector(".editor-nav"),label,()=>showTab(label),""); tab.id="tab-"+label.toLowerCase();tab.setAttribute("role","tab");tab.setAttribute("aria-controls","editor-content");tab.setAttribute("aria-selected","false");tab.tabIndex=-1; });
  document.querySelector(".editor-nav").addEventListener("keydown",event=>{
    if (!["ArrowDown","ArrowUp","ArrowLeft","ArrowRight","Home","End"].includes(event.key)) return;
    event.preventDefault();let index=tabs.indexOf(activeTab);
    if(event.key==="Home")index=0;else if(event.key==="End")index=tabs.length-1;else index=(index+(["ArrowDown","ArrowRight"].includes(event.key)?1:-1)+tabs.length)%tabs.length;
    showTab(tabs[index]);document.getElementById("tab-"+tabs[index].toLowerCase()).focus();
  });
  document.getElementById("login-form").addEventListener("submit",async event=>{
    if (publisher?.server || publisher?.configured) { event.preventDefault(); return; }
    event.preventDefault();const input=document.getElementById("password");const loginStatus=document.getElementById("login-status");const submit=event.currentTarget.querySelector("button");submit.disabled=true;
    try {
      if(!window.crypto?.subtle)throw new Error("Open this editor over HTTPS or a local development server.");
      const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(input.value));
      const hash=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join("");input.value="";
      if(hash!==ADMIN_PASSWORD_SHA256)throw new Error("That password doesn’t match. Please try again.");
      authenticated=true;draft=app.load();dirty=false;document.getElementById("login-section").hidden=true;dashboard.hidden=false;showTab("Hero");syncPreview();document.getElementById("tab-hero").focus();notify(app.storageWarning||"Ready to edit.",Boolean(app.storageWarning));loginStatus.textContent="";
    }catch(error){loginStatus.textContent=error.message;loginStatus.classList.add("error");input.focus();}finally{submit.disabled=false;}
  });
  document.getElementById("save").addEventListener("click",()=>{
    if(!authenticated)return;
    try{draft=app.save(draft);dirty=false;syncPreview();notify(publisher?.server ? "Draft saved in this browser. Choose Publish to GitHub when it is ready to go live." : "Draft saved in this browser. Use Backups to export it for publication.");}
    catch(error){notify(error.name==="QuotaExceededError"?"Browser storage is full. Export a backup before clearing space.":error.name==="SecurityError"?"This browser has blocked storage. Export a backup to keep your edits.":error.message,true);}
  });
  document.getElementById("logout").addEventListener("click",()=>confirmAction("Your unsaved draft will be discarded when you log out.",async()=>{
    try { if (publisher?.server) await publisher.logout(); }
    catch (error) { notify(error.message, true); return; }
    authenticated=false;draft=null;dirty=false;remoteHead="";pendingPublish=null;content.replaceChildren();dashboard.hidden=true;document.getElementById("login-section").hidden=false;
    (publisher?.configured ? document.getElementById("github-login") : document.getElementById("password")).focus();
    preview.contentWindow?.Portfolio?.render(app.load());
  }));
  document.getElementById("backup-shortcut").addEventListener("click",()=>{showTab("Backups");content.focus();});
  preview.addEventListener("load",syncPreview);
  window.addEventListener("beforeunload",event=>{if(dirty || publishing){event.preventDefault();event.returnValue="";}});
  window.addEventListener("storage",event=>{if(authenticated&&event.key===app.storageKey)notify("Content changed in another tab. Export your draft before reloading if you want to keep it.");});

  document.getElementById("publish").addEventListener("click", async () => {
    if (!authenticated || !publisher?.server || publishing) return;
    const publishStatus = document.getElementById("publish-status");
    publishing = true;
    dashboard.inert = true;
    dashboard.setAttribute("aria-busy", "true");
    publishStatus.classList.remove("error");
    publishStatus.textContent = "Publishing your portfolio and SEO page to GitHub…";
    try {
      const clean = app.validate(draft);
      pendingPublish ||= crypto.randomUUID();
      const result = await publisher.publish(clean, remoteHead, pendingPublish);
      remoteHead = result.commit;
      pendingPublish = null;
      draft = clean;
      dirty = false;
      try { app.save(clean); } catch {}
      publishStatus.replaceChildren(node("span", "", "Published to GitHub. The live website will update after deployment. "));
      const commitLink = node("a", "", "View commit ↗");
      commitLink.href = result.commitUrl;
      commitLink.target = "_blank";
      commitLink.rel = "noopener noreferrer";
      publishStatus.append(commitLink);
      notify("Your portfolio content and search information were published together.");
    } catch (error) {
      publishStatus.classList.add("error");
      publishStatus.textContent = error.message;
      if (error.status === 401) {
        const signIn = node("a", "", " Save a draft, then sign in again ↗");
        signIn.href = publisher.loginUrl;
        publishStatus.append(signIn);
      }
    } finally {
      publishing = false;
      dashboard.inert = false;
      dashboard.removeAttribute("aria-busy");
    }
  });

  async function connectGitHub() {
    const loginLink = document.getElementById("github-login");
    const loginStatus = document.getElementById("github-login-status");
    if (publisher?.server) {
      document.getElementById("local-login").hidden = true;
      document.querySelectorAll(".admin-header a").forEach(anchor => { anchor.href = "https://salehahmed101.github.io/"; });
      if (!publisher.configured) document.getElementById("connection-help").textContent = "GitHub publishing needs its one-time setup before you can sign in.";
    }
    if (!publisher?.configured) return;
    document.getElementById("local-login").hidden = true;
    document.getElementById("connection-help").textContent = "Sign in with your GitHub account to edit and publish your portfolio.";
    loginLink.href = publisher.loginUrl;
    loginLink.hidden = false;
    if (!publisher.server) return;
    loginStatus.textContent = "Checking your GitHub session…";
    try {
      const session = await publisher.connect();
      const published = await publisher.load();
      draft = app.validate(published.data);
      remoteHead = published.head;
      authenticated = true;
      dirty = false;
      document.getElementById("login-section").hidden = true;
      dashboard.hidden = false;
      document.getElementById("publish").hidden = false;
      document.getElementById("editor-notice").textContent = "Connected as " + session.login + ". Save draft keeps a local backup; Publish to GitHub updates your live portfolio and SEO page together.";
      showTab("Hero");
      syncPreview();
      notify("Loaded the latest published content from GitHub. Previous browser drafts are available in Backups.");
      loginStatus.textContent = "";
    } catch (error) {
      loginStatus.textContent = error.status === 401 ? "Sign in to begin editing." : error.message;
      loginStatus.classList.toggle("error", error.status !== 401);
    }
  }
  connectGitHub();
})();
