(() => {
  "use strict";
  // This is a browser-side convenience gate, not server-side authentication.
  // Replace the hash below with the SHA-256 hash of your chosen password.
  const ADMIN_PASSWORD_SHA256 = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9";
  const app = window.Portfolio;
  const dashboard = document.getElementById("dashboard");
  const content = document.getElementById("editor-content");
  const preview = document.querySelector(".editor-preview iframe");
  const status = document.getElementById("editor-status");
  const tabs = ["Hero","About","Skills","Experience","Projects","Education","Contact","Headings","Backups"];
  let authenticated = false;
  let draft = null;
  let activeTab = "Hero";
  let dirty = false;
  let pendingConfirmation = null;
  let importedInput = null;
  const dialog = document.getElementById("confirm-dialog");
  const node = (tag, className, text) => { const result = document.createElement(tag); if (className) result.className = className; if (text !== undefined) result.textContent = app.noDigits(text); return result; };
  function notify(message, error = false) { status.textContent = app.noDigits(message); status.classList.toggle("error", error); }
  function syncPreview() { if (authenticated) preview.contentWindow?.Portfolio?.render(draft); }
  function changed() { dirty = true; notify("Unsaved changes. Your preview is up to date."); syncPreview(); }
  function confirmAction(message, action) {
    if (!dirty) { action(); return; }
    pendingConfirmation = action; document.getElementById("confirm-message").textContent = message; dialog.showModal();
  }
  document.getElementById("confirm-cancel").addEventListener("click", () => { pendingConfirmation = null; dialog.close(); });
  document.getElementById("confirm-accept").addEventListener("click", () => { const action = pendingConfirmation; pendingConfirmation = null; dialog.close(); action?.(); });
  dialog.addEventListener("cancel", () => { pendingConfirmation = null; });
  function textField(parent, label, value, onChange, options = {}) {
    const wrapper = node("label", "field" + (options.wide ? " wide" : "")); wrapper.append(node("span", "", label));
    const input = node(options.multiline ? "textarea" : "input");
    if (!options.multiline) input.type = "text";
    input.value = app.encode(value); input.maxLength = 12000; input.spellcheck = !options.link;
    input.addEventListener("input", () => {
      const start = input.selectionStart;
      const left = app.encode(input.value.slice(0, start));
      input.value = app.encode(input.value); input.setSelectionRange(left.length, left.length);
      onChange(app.decode(input.value)); changed();
    }); wrapper.append(input); parent.append(wrapper); return input;
  }
  function fields(parent, model, definitions) {
    const grid = node("div", "editor-grid");
    definitions.forEach(([key, label, multiline = false, link = false]) => textField(grid, label, model[key], value => { model[key] = value; }, {multiline, wide:multiline, link}));
    parent.append(grid);
  }
  function button(parent, label, action, className = "button secondary") { const result = node("button", className, label); result.type = "button"; result.addEventListener("click", action); parent.append(result); return result; }
  function listEditor(key, singular, makeItem, definitions, extra) {
    if (!draft[key].length) content.append(node("p", "empty-note", "Nothing here yet. Add an entry to get started."));
    draft[key].forEach((item, index) => {
      const card = node("article", "editor-item"); const header = node("div", "editor-item-header");
      header.append(node("h3", "", item.title || item.name || item.degree || "New " + singular.toLowerCase()));
      button(header, "Remove", () => { draft[key].splice(index, 1); changed(); showTab(activeTab); }, "small-button remove-button"); card.append(header);
      fields(card, item, definitions); extra?.(card, item); content.append(card);
    });
    button(content, "Add " + singular.toLowerCase(), () => { draft[key].push(makeItem()); changed(); showTab(activeTab); content.querySelector(".editor-item:last-of-type input")?.focus(); });
  }
  function download(filename, text, type) {
    const url = URL.createObjectURL(new Blob([text], {type})); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  function safeExport(publication = false) {
    try {
      const clean = app.validate(draft);
      if (publication) download("data.js", "// Published portfolio content. Generated by the portfolio editor.\nwindow.PORTFOLIO_DEFAULTS = " + JSON.stringify(clean, null, 2) + ";\n", "text/javascript");
      else download("portfolio-backup.json", JSON.stringify(clean, null, 2), "application/json");
      notify(publication ? "Publication file exported. Replace the matching file inside the JavaScript folder on GitHub." : "Backup exported, including your current draft.");
    } catch(error) { notify(error.message, true); }
  }
  function backups() {
    content.append(node("p", "backup-note", "Export JSON to keep a backup of your current draft. Import a backup to preview its content, then choose Save Changes to keep it in this browser."));
    const actions = node("div", "backup-actions"); button(actions, "Export JSON", () => safeExport());
    importedInput = node("input"); importedInput.type = "file"; importedInput.accept = ".json,application/json"; importedInput.hidden = true;
    button(actions, "Import JSON", () => importedInput.click());
    importedInput.addEventListener("change", async () => {
      const file = importedInput.files[0]; if (!file) return;
      try {
        if (file.size > 1000000) throw new Error("This backup is too large.");
        const imported = app.validate(JSON.parse(await file.text()));
        confirmAction("Importing replaces the current draft. Export a backup first if you want to keep it.", () => { draft = imported; changed(); notify("Backup imported as a draft. Review the preview, then save your changes."); showTab("Hero"); });
      } catch(error) { notify(error instanceof SyntaxError ? "This file is not valid JSON. Choose a portfolio backup." : error.message, true); }
      importedInput.value = "";
    }); content.append(actions, importedInput);
    content.append(node("h3", "", "Publish your edits")); content.append(node("p", "backup-note", "Export the publication file and upload it into the JavaScript folder in your GitHub repository, replacing the existing data file. GitHub Pages will publish the new content for everyone. Browser saves alone do not update the shared website."));
    button(content, "Export publication file", () => safeExport(true));
  }
  function showTab(label) {
    if (!authenticated) return;
    activeTab = label; content.replaceChildren(node("h2", "", label)); content.setAttribute("aria-labelledby", "tab-" + label.toLowerCase());
    document.querySelectorAll(".editor-nav button").forEach(tab => { const selected = tab.textContent === label; tab.setAttribute("aria-selected", String(selected)); tab.tabIndex = selected ? 0 : -1; });
    if (label === "Hero") fields(content, draft.hero, [["name","Name"],["title","Professional title"],["tagline","Tagline",true],["status","Availability"],["location","Location line"],["primaryLabel","Primary button label"],["primaryUrl","Primary button link",false,true],["secondaryLabel","Secondary button label"],["secondaryUrl","Secondary button link",false,true],["focusLabel","Feature card introduction"],["focusKicker","Feature card label"],["focusTitle","Feature card headline",true],["focusFooter","Feature card footer",true]]);
    if (label === "About") fields(content, draft.about, [["heading","Heading",true],["text","About you",true],["learning","Learning interests",true]]);
    if (label === "Skills") listEditor("skills","Skill",() => ({name:"New skill",percentage:null}),[["name","Skill name"]],(card,skill) => {
      const checkLabel = node("label","check-label"); const check = node("input"); check.type="checkbox"; check.checked=skill.percentage!==null; checkLabel.append(check,node("span","","Show self-assessed proficiency")); card.append(checkLabel);
      const rangeLabel = node("label","field"); rangeLabel.hidden=!check.checked; rangeLabel.append(node("span","","Proficiency")); const range=node("input"); range.type="range"; range.min="0";range.max="100";range.value=skill.percentage??50;range.setAttribute("aria-valuetext",app.noDigits(range.value)+" percent");rangeLabel.append(range); card.append(rangeLabel);
      check.addEventListener("change",()=>{skill.percentage=check.checked?Number(range.value):null;rangeLabel.hidden=!check.checked;changed();});
      range.addEventListener("input",()=>{skill.percentage=Number(range.value);range.setAttribute("aria-valuetext",app.noDigits(range.value)+" percent");changed();});
    });
    if (label === "Experience") listEditor("experience","Experience",()=>({title:"New role",company:"",location:"",period:"",bullets:[]}),[["title","Job title"],["company","Employer"],["location","Location"],["period","Dates written in words"]],(card,item)=>textField(card,"Highlights — each on its own line",item.bullets.join("\n"),value=>{item.bullets=value.split("\n").filter(line=>line.trim());},{multiline:true}));
    if (label === "Projects") listEditor("projects","Project",()=>({title:"New project",category:"",description:"",institution:"",tags:[],url:"",linkLabel:"View project"}),[["title","Project name"],["category","Category"],["description","Description",true],["institution","Institution or context"],["url","Project link",false,true],["linkLabel","Link label"]],(card,item)=>textField(card,"Tags — each on its own line",item.tags.join("\n"),value=>{item.tags=value.split("\n").filter(line=>line.trim());},{multiline:true}));
    if (label === "Education") listEditor("education","Education",()=>({degree:"New qualification",institution:"",period:"",description:""}),[["degree","Qualification"],["institution","Institution"],["period","Dates written in words"],["description","Additional details",true]]);
    if (label === "Contact") { fields(content,draft.contact,[["eyebrow","Introductory label"],["heading","Heading",true],["text","Invitation",true],["email","Email address",false,true],["phone","Phone number",false,true],["linkedin","LinkedIn profile link",false,true],["location","Location"],["emailLabel","Email button label"],["phoneLabel","Phone button label"],["linkedinLabel","LinkedIn button label"]]);content.append(node("p","muted","Leave LinkedIn blank until your profile link is ready.")); }
    if (label === "Headings") fields(content,draft.headings,[["skills","Skills heading"],["experience","Experience heading"],["projects","Projects heading"],["projectsIntro","Projects introduction",true],["education","Education heading"],["footer","Footer text",true]]);
    if (label === "Backups") backups();
  }
  tabs.forEach(label => { const tab = button(document.querySelector(".editor-nav"),label,()=>showTab(label),""); tab.id="tab-"+label.toLowerCase();tab.setAttribute("role","tab");tab.setAttribute("aria-controls","editor-content");tab.setAttribute("aria-selected","false");tab.tabIndex=-1; });
  document.querySelector(".editor-nav").addEventListener("keydown",event=>{
    if (!["ArrowDown","ArrowUp","ArrowLeft","ArrowRight","Home","End"].includes(event.key)) return;
    event.preventDefault();let index=tabs.indexOf(activeTab);
    if(event.key==="Home")index=0;else if(event.key==="End")index=tabs.length-1;else index=(index+(["ArrowDown","ArrowRight"].includes(event.key)?1:-1)+tabs.length)%tabs.length;
    showTab(tabs[index]);document.getElementById("tab-"+tabs[index].toLowerCase()).focus();
  });
  document.getElementById("login-form").addEventListener("submit",async event=>{
    event.preventDefault();const input=document.getElementById("password");const loginStatus=document.getElementById("login-status");const submit=event.currentTarget.querySelector("button");submit.disabled=true;
    try {
      if(!window.crypto?.subtle)throw new Error("Open this editor over HTTPS or a local development server.");
      const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(input.value));
      const hash=Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join("");input.value="";
      if(hash!==ADMIN_PASSWORD_SHA256)throw new Error("That password doesn’t match. Please try again.");
      authenticated=true;draft=app.load();dirty=false;document.getElementById("login-section").hidden=true;dashboard.hidden=false;showTab("Hero");syncPreview();document.getElementById("tab-hero").focus();notify(app.storageWarning||"Ready to edit.",Boolean(app.storageWarning));loginStatus.textContent="";
    }catch(error){loginStatus.textContent=error.message;loginStatus.classList.add("error");input.focus();}finally{submit.disabled=false;}
  });
  document.getElementById("save").addEventListener("click",()=>{
    if(!authenticated)return;
    try{draft=app.save(draft);dirty=false;syncPreview();notify("Saved in this browser. Export a publication file to update the shared website.");}
    catch(error){notify(error.name==="QuotaExceededError"?"Browser storage is full. Export a backup before clearing space.":error.name==="SecurityError"?"This browser has blocked storage. Export a backup to keep your edits.":error.message,true);}
  });
  document.getElementById("logout").addEventListener("click",()=>confirmAction("Your unsaved draft will be discarded when you log out.",()=>{authenticated=false;draft=null;dirty=false;content.replaceChildren();dashboard.hidden=true;document.getElementById("login-section").hidden=false;document.getElementById("password").focus();preview.contentWindow?.Portfolio?.render(app.load());}));
  document.getElementById("backup-shortcut").addEventListener("click",()=>{showTab("Backups");content.focus();});
  preview.addEventListener("load",syncPreview);
  window.addEventListener("beforeunload",event=>{if(dirty){event.preventDefault();event.returnValue="";}});
  window.addEventListener("storage",event=>{if(authenticated&&event.key===app.storageKey)notify("Content changed in another tab. Export your draft before reloading if you want to keep it.");});
})();
